#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=33
TOTAL_MINUTES=145

# Wizard state: VPS_IP, TS_IP, GH_PAT*, APP_DOMAIN, COOLIFY_ADMIN_* — gitignored.
ENV_FILE=".wayfinder-vps.env"
# Repo root — the wizard lives in scripts/.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Ubuntu user on Oracle A1 images.
VPS_USER="ubuntu"

banner "Oracle Cloud VPS migration — wayfinder chain + Coolify deploy"

# ── Phase 0 — pre-flight (this machine) ────────────────────────────────────

stage "Pre-flight — branch state" 2
say "Your session record before the move:"
git -C "$REPO" log --oneline -1
note "branch: $(git -C "$REPO" branch --show-current) — ahead of origin by $(git -C "$REPO" rev-list --count origin/master..HEAD 2>/dev/null || echo '?') commits"
git -C "$REPO" status --short | head -10
command -v gh >/dev/null 2>&1 && gh issue list --state open --limit 10 || warn "gh not available locally"
pause "Noted the session number + branch state"

stage "Push the branch now?" 4
say "The VPS needs ralph/company-app-full-build on GitHub to clone it (and Coolify pulls it too)."
say "Pushing now is safe — sessions commit locally, they don't push."
if confirm "Push the branch to origin now"; then
  git -C "$REPO" push
  note "pushed (pre-push gate ~3 min)"
else
  warn "deferred — pushed at the switch stage (stage 30); Coolify deploy must wait for it"
fi

# ── Phase 1 — Oracle VM + first access ─────────────────────────────────────

stage "SSH key" 1
if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
  note "key exists: $HOME/.ssh/id_ed25519.pub"
else
  say "No SSH key on this machine — creating one (empty passphrase)."
  confirm "Create ed25519 key at ~/.ssh/id_ed25519?" || { warn "create it yourself: ssh-keygen -t ed25519"; pause "key created?"; }
  if [[ ! -f "$HOME/.ssh/id_ed25519.pub" ]]; then
    mkdir -p "$HOME/.ssh" && ssh-keygen -q -t ed25519 -N "" -C "$(whoami)@$(hostname)-vps" -f "$HOME/.ssh/id_ed25519"
  fi
fi
note "your public key (paste into the Oracle console next):"
cat "$HOME/.ssh/id_ed25519.pub"

stage "Oracle console — create the VM" 15
open_url "https://cloud.oracle.com"
step "Sign in → Compute → Instances → Create instance"
step "Name: company-vps"
step "Image: Ubuntu 24.04 (aarch64 ARM64)"
step "Shape: VM.Standard.A1.Flex — set 2 OCPUs / 12 GB RAM (the free-tier cap)"
warn "A1 is often 'Out of capacity' in busy regions — retry your home region or a different availability domain"
step "Boot volume: 47 GB or larger (free tier includes 200 GB total)"
step "Networking: assign a RESERVED public IPv4 if offered (ephemeral works too — but a reserved IP keeps the nip.io name stable)"
step "Add SSH key: paste the public key shown above"
note "No extra ingress — everything binds localhost; only SSH (22) is needed at first"
pause "Instance created — note its public IP"

stage "Capture the public IP" 2
ask VPS_IP "Paste the instance public IP:"
write_env VPS_IP "$VPS_IP"
pause "Press Enter to test SSH (first connect accepts the host key)"

stage "Verify SSH via public IP" 2
note "connecting…"
if ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20 "$VPS_USER@$VPS_IP" 'uname -m; lsb_release -d' ; then
  note "ssh works"
else
  warn "ssh failed — check the IP, the key, and that the instance is RUNNING (not Provisioning/Stopped)"
  pause "Fixed? Press Enter to retry" && ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20 "$VPS_USER@$VPS_IP" 'uname -m'
fi

# ── Phase 2 — Tailscale ────────────────────────────────────────────────────

stage "Tailscale auth key" 2
open_url "https://login.tailscale.com/admin/settings/keys"
step "Generate an auth key (ephemeral is fine — it is used once)"
ask_secret TS_AUTHKEY "Paste the Tailscale auth key:"

stage "Join the tailnet" 5
if TS_IP=$(_existing TS_IP || true) && [[ -n "$TS_IP" ]] && ssh -o ConnectTimeout=10 "$VPS_USER@$TS_IP" 'true' 2>/dev/null; then
  note "already on the tailnet at $TS_IP — skipping"
else
  note "installing tailscale on the VPS and joining (via public IP)…"
  ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" \
    'curl -fsSL https://tailscale.com/install.sh | sudo sh && sudo tailscale up --authkey '"$TS_AUTHKEY"' --hostname company-vps'
  TS_IP="$(ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" 'tailscale ip -4' | tr -d '[:space:]')"
  [[ -n "$TS_IP" ]] || { warn "no tailnet IP — is the auth key valid/expired?"; pause "fix, then press Enter" ; TS_IP="$(ssh "$VPS_USER@$VPS_IP" 'tailscale ip -4' | tr -d '[:space:]')" ; }
  write_env TS_IP "$TS_IP"
fi
note "tailnet IP: $TS_IP"
if ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 "$VPS_USER@$TS_IP" 'true'; then
  note "✓ ssh via tailnet works — all later stages use the tailnet IP"
else
  warn "ssh over tailnet failed — is this machine logged into the same tailnet?"
  pause "Press Enter once ssh ubuntu@$TS_IP works"
fi

# ssh/scp helpers — everything below rides the tailnet.
vps()   { ssh -o ConnectTimeout=15 "$VPS_USER@$TS_IP" "$@"; }
vpsscp() { scp -o ConnectTimeout=15 "$@"; }

# ── Phase 3 — VPS bootstrap (scripted over tailnet) ────────────────────────

stage "Base packages" 6
vps 'sudo apt-get update && sudo apt-get install -y openjdk-21-jdk git tmux curl unzip npm gh docker.io docker-compose-plugin'
vps 'java -version 2>&1 | head -1; tmux -V; gh --version | head -1'

stage "Docker service" 3
vps 'sudo usermod -aG docker '"$VPS_USER"' && sudo systemctl enable --now docker'
vps 'docker --version && docker compose version'
note "docker group applies to new sessions — each stage is a fresh ssh, so it is already active"

stage "GitHub CLI auth" 5
open_url "https://github.com/settings/tokens/new"
step "Create a CLASSIC token with the repo scope (covers issues + git-credential)"
ask_secret GH_PAT "Paste the GitHub PAT (repo scope):"
printf '%s' "$GH_PAT" | vps 'gh auth login --with-token'
vps 'gh auth status'
note "PAT consumed by the VPS — nothing written to disk locally"

stage "opencode2 (pinned)" 3
vps 'sudo npm install -g @opencode-ai/cli@0.0.0-next-17444'
vps 'opencode2 --version'

stage "Copy opencode config + keys" 3
vps 'mkdir -p ~/.config ~/.local/share/opencode'
vpsscp -r "$HOME/.config/opencode" "$VPS_USER@$TS_IP":~/.config/
vpsscp "$HOME/.local/share/opencode/auth.json" "$VPS_USER@$TS_IP":~/.local/share/opencode/auth.json
warn "deliberately NOT copying ~/.local/share/opencode/opencode.db (2.1 GB session state — VPS starts fresh)"
vps 'du -sh ~/.config/opencode; wc -c ~/.local/share/opencode/auth.json'

stage "Start the opencode service" 2
vps 'opencode2 serve --service'
sleep 3
vps 'opencode2 api get /api/model'
pause "Does the model response above look right? (not an error)"

stage "Clone the repo" 3
vps 'git clone https://github.com/jsongalvez/company_app.git ~/company_app'
if vps 'git -C ~/company_app switch ralph/company-app-full-build'; then
  note "branch checked out"
else
  warn "branch not on origin yet — it lands at the switch push (stage 30); the switch stage checks it out"
  vps 'git -C ~/company_app switch master'
fi
vps 'git -C ~/company_app log --oneline -1'

stage "Copy secrets (.env, .wayfinder-loop.env)" 2
[[ -f "$REPO/.env" ]] && vpsscp "$REPO/.env" "$VPS_USER@$TS_IP":~/company_app/.env
[[ -f "$REPO/.wayfinder-loop.env" ]] && vpsscp "$REPO/.wayfinder-loop.env" "$VPS_USER@$TS_IP":~/company_app/.wayfinder-loop.env
warn "secrets now on the VPS — keep the ntfy topic + creds off any logs"
vps 'wc -c ~/company_app/.env ~/company_app/.wayfinder-loop.env'

stage "Postgres 18 (gate DB)" 4
vps 'cd ~/company_app && docker compose -f docker/docker-compose.yml up -d'
for i in $(seq 1 12); do
  sleep 10
  if vps "cd ~/company_app && docker compose -f docker/docker-compose.yml ps" | grep -q healthy; then
    note "postgres healthy"; break
  fi
  [[ $i -eq 12 ]] && warn "postgres not healthy yet — check: docker compose -f docker/docker-compose.yml ps"
done

stage "Git hooks + ktlint" 2
vps 'cd ~/company_app && bash scripts/setup-hooks.sh'

stage "Warm the build gate" 16
note "first Gradle run downloads the toolchain + deps (~10-15 min). Launched in background; the wizard polls."
vps 'cd ~/company_app && nohup ./gradlew :backend:detekt :backend:ktlintCheck :backend:test :composeApp:compileKotlinDesktop > /tmp/gate-warm.log 2>&1 &'
for i in $(seq 1 40); do
  sleep 30
  last="$(vps 'tail -n 1 /tmp/gate-warm.log' | tr -d '\r')"
  printf '  %s%s\n' "$DIM" "$last"
  if vps 'grep -qE "BUILD (SUCCESSFUL|FAILED)" /tmp/gate-warm.log'; then break; fi
done
vps 'tail -n 3 /tmp/gate-warm.log'

# ── Phase 4 — harden ───────────────────────────────────────────────────────

stage "Firewall (ufw)" 3
vps 'sudo ufw default deny incoming && sudo ufw default allow outgoing && sudo ufw allow in on tailscale0 && sudo ufw allow 80/tcp && sudo ufw allow 443/tcp && sudo ufw allow 41641/udp && sudo ufw --force enable'
vps 'sudo ufw status verbose'
note "ssh = tailnet only (via tailscale0); 80/443 public for Coolify + the app; 41641/udp = tailscale direct connections"

stage "SSH hardening" 2
vps 'printf "PermitRootLogin no\nPasswordAuthentication no\n" | sudo tee /etc/ssh/sshd_config.d/99-hardening.conf && sudo systemctl restart ssh'
vps 'sudo sshd -T | grep -E "^(permitrootlogin|passwordauthentication)"'

stage "Unattended security upgrades" 2
vps 'sudo apt-get install -y unattended-upgrades && sudo systemctl enable --now unattended-upgrades'
vps 'sudo sed -i "s|//[[:space:]]*\"\${distro_id}:\${distro_codename}\";|\"\${distro_id}:\${distro_codename}\";|" /etc/apt/apt.conf.d/50unattended-upgrades'
vps 'systemctl is-enabled unattended-upgrades'

stage "Oracle security list (2nd firewall layer)" 5
open_url "https://cloud.oracle.com"
step "Networking → Virtual cloud networks → your VCN → Security Lists → Default Security List"
step "Edit ingress rules: REMOVE 22/tcp from 0.0.0.0/0 (public SSH dies here — tailnet ssh is unaffected)"
step "ADD 80/tcp and 443/tcp from 0.0.0.0/0 (Coolify + the app)"
note "Security list + ufw = the two independent layers from docs/architecture.md"
pause "Security list updated?"

# ── Phase 5 — Coolify + app deploy ─────────────────────────────────────────

stage "Install Coolify" 8
note "installing (downloads ~5 min)…"
vps 'curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash'
sleep 3
vps 'curl -sf http://127.0.0.1:8000/api/health' && note "✓ Coolify API is up"

stage "Coolify dashboard first run" 5
open_url "http://$TS_IP:8000"
step "Create the admin account (email + password) — the wizard remembers them for re-runs"
ask COOLIFY_ADMIN_EMAIL "Coolify admin email:"
write_env COOLIFY_ADMIN_EMAIL "$COOLIFY_ADMIN_EMAIL"
ask_secret COOLIFY_ADMIN_PASSWORD "Coolify admin password:"
write_env COOLIFY_ADMIN_PASSWORD "$COOLIFY_ADMIN_PASSWORD"
step "Instance domain: leave as-is (http://$TS_IP:8000)"
step "Skip/close any onboarding prompts (notifications, etc.)"
pause "Dashboard visible?"

stage "Backend Dockerfile" 4
if [[ ! -f "$REPO/backend/Dockerfile" ]]; then
  warn "backend/Dockerfile missing — create it (multi-stage: gradle wrapper → temurin 21 → installDist), then commit + push"
  pause "Dockerfile in place and pushed?"
fi
if [[ -f "$REPO/backend/Dockerfile" ]]; then
  note "backend/Dockerfile present ✓"
  if git -C "$REPO" status --porcelain backend/Dockerfile | grep -q .; then
    confirm "Commit + push the Dockerfile now (Coolify needs it on GitHub)?" && \
      git -C "$REPO" add backend/Dockerfile && \
      git -C "$REPO" commit -m "feat(infra): backend Dockerfile for Coolify deploy" && \
      git -C "$REPO" push
  fi
fi

stage "Coolify — Postgres resource" 5
open_url "http://$TS_IP:8000"
step "Projects → New Project (e.g. company) → inside it: + New Resource → Postgres"
step "Set POSTGRES_DB / POSTGRES_USER / POSTGRES_PASSWORD to the values from your repo .env (paste from below):"
note "  — values below are read from your local .env —"
for k in POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD; do
  note "  $k=$(grep -E "^$k=" "$REPO/.env" | head -1 | cut -d= -f2-)"
done
step "Deploy the Postgres resource and wait for it to run"
pause "Postgres resource running? Note its internal hostname (usually 'postgres')"

stage "Coolify — the app resource" 8
open_url "http://$TS_IP:8000"
step "+ New Resource → Public Repository"
step "Git repository: https://github.com/jsongalvez/company_app.git"
step "Branch: ralph/company-app-full-build"
step "Build pack: Dockerfile"
step "Dockerfile location: /backend/Dockerfile"
step "Ports Exposes: $(grep -E '^APP_PORT=' "$REPO/.env" | head -1 | cut -d= -f2- || echo 'your APP_PORT from .env')"
step "Domains: api.$VPS_IP.nip.io (enable HTTPS — Let's Encrypt)"
step "Environment variables — copy from the block below:"
note "  APP_HOST=0.0.0.0"
note "  APP_PORT=$(grep -E '^APP_PORT=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<APP_PORT from .env>')"
note "  DB_HOST=postgres   # the Postgres resource's internal hostname"
note "  DB_PORT=5432"
note "  POSTGRES_DB=$(grep -E '^POSTGRES_DB=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  POSTGRES_USER=$(grep -E '^POSTGRES_USER=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  POSTGRES_PASSWORD=$(grep -E '^POSTGRES_PASSWORD=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  JWT_SECRET=$(grep -E '^JWT_SECRET=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  JWT_ISSUER=$(grep -E '^JWT_ISSUER=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  JWT_AUDIENCE=$(grep -E '^JWT_AUDIENCE=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  AUTH_DUMMY_PASSWORD=$(grep -E '^AUTH_DUMMY_PASSWORD=' "$REPO/.env" | head -1 | cut -d= -f2- || echo '<from .env>')"
note "  (skip TEST_USERNAME/TEST_PASSWORD — test seeding stays off in prod)"
step "Deploy, then watch the build log (~5-10 min first build: Gradle downloads)"
pause "Build finished (success or visible failure)?"

stage "Verify the deployed backend" 10
if confirm "Try the HTTPS health check now?"; then
  code="$(curl -sk -o /dev/null -w '%{http_code}' "https://api.$VPS_IP.nip.io/health" || true)"
  note "https://api.$VPS_IP.nip.io/health → HTTP $code"
  curl -sk "https://api.$VPS_IP.nip.io/health" && echo
  if [[ "$code" == "200" ]]; then
    note "✓ deployed backend is live over HTTPS"
  else
    warn "not 200 — check the Coolify build log + app logs; DB_HOST must match the Postgres resource name"
    pause "press Enter after the deploy is fixed"
  fi
fi

# ── Phase 6 — the switch (CRITICAL: never two daemons) ─────────────────────

stage "Boundary check" 2
HANDOFF="$(ls -t "$REPO"/docs/agents/wayfinder-*-handoff.md 2>/dev/null | head -1 | xargs -n1 basename 2>/dev/null || true)"
note "latest handoff: ${HANDOFF:-none found}"
git -C "$REPO" log --oneline -3
if [[ -n "$HANDOFF" ]] && git -C "$REPO" status --porcelain | grep -q "wayfinder-"; then
  warn "the handoff is NOT committed yet — it must land before the switch"
fi
pause "Session N complete — handoff committed, and the next session number is the one that handoff names?"

stage "Push the branch (carries the handoff)" 4
if [[ -n "$(git -C "$REPO" log --oneline origin/master..HEAD 2>/dev/null)" ]]; then
  git -C "$REPO" push
  note "pushed (~3 min pre-push gate)"
else
  note "already up to date"
fi

stage "Kill the local daemon" 2
warn "Rollback if anything fails below: tmux new -s wayfinder-loop && ./scripts/wayfinder-loop.sh"
if confirm "Kill the local wayfinder-loop daemon NOW (this is the switch)?"; then
  tmux kill-session -t wayfinder-loop 2>/dev/null || true
  sleep 2
  if tmux ls 2>/dev/null | grep -q wayfinder-loop || pgrep -f wayfinder-loop.sh >/dev/null; then
    warn "daemon still alive — kill it manually (tmux kill-session -t wayfinder-loop)"
    pause "daemon dead?"
  else
    note "✓ local daemon dead"
  fi
else
  warn "switch skipped — the VPS daemon MUST NOT start while the local one lives"
  pause "press Enter to continue anyway (VPS daemon start is next)"
fi

stage "Start the VPS daemon" 5
vps "cd ~/company_app && git fetch origin && (git switch ralph/company-app-full-build 2>/dev/null || git switch -C ralph/company-app-full-build origin/ralph/company-app-full-build) && git pull --ff-only && tmux new-session -d -s wayfinder-loop \"bash -lc 'cd ~/company_app && ./scripts/wayfinder-loop.sh --bootstrap ${HANDOFF:-wayfinder-latest-handoff.md}'\""
sleep 15
vps 'tail -n 20 ~/company_app/.wayfinder-loop.log'
note "expect a line like: spawned ses_… reading <handoff>.md"
pause "ntfy topic fired ('wayfinder session started')?"

stage "Post-migration checks" 3
vps 'cd ~/company_app && gh issue view 89 --json number,title,state -q ".number + \" \" + .title + \" (\" + .state + \")\""'
note "map reachable from the VPS ✓ — first VPS pre-commit gate runs on the next session commit (watch it succeed end-to-end)"
note "k6 skipped (optional): pre-push warns + skips the load test on the VPS"
note "next session on the VPS works the map as usual — same branch, same issues"

finish
