#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
# Library extension in this file: ask() takes an optional 3rd arg = default
# (Enter accepts it; a saved .wayfinder-vps.env value still wins). Fold this
# back into the wizard template when the template next evolves.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" [default] — read a value into $KEY. Shows the default
# (existing .env value on re-runs, or the passed default on first run);
# Enter keeps it. Blank with neither stays empty (the caller aborts).
ask() {
  local key="$1" prompt="$2" fallback="${3:-}" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  elif [[ -n "$fallback" ]]; then
    printf '  %s%s%s %s[default: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$fallback" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  [[ -z "$input" && -n "$fallback" ]] && input="$fallback"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Wizard state: MODE, SSH_MODE, TS_HOSTNAME, VPS_USER, REPO_URL, DEPLOY_BRANCH,
# APP_DOMAIN, VPS_IP, TS_IP, COOLIFY_ADMIN_* — gitignored.
# Repo root — the wizard lives in scripts/.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO/.wayfinder-vps.env"

# abort "msg" — warn + exit 1 (the wizard's loud-stop idiom). Defined before
# the first call site — bash resolves functions at call time.
abort() { warn "$1"; exit 1; }

# env_val KEY [fallback] — the value of KEY from the repo .env, or the
# fallback (default '<from .env>') when the key is absent.
env_val() { grep -E "^$1=" "$REPO/.env" 2>/dev/null | head -1 | cut -d= -f2- || printf '%s' "${2:-<from .env>}"; }

# IPv4 shape — one definition for both the VPS_IP and TS_IP gates.
IPV4_RE='(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])'

# latest_handoff EMPTY_ABORT_MSG — sets HANDOFF to the newest
# docs/agents/wayfinder-<N>-handoff.md basename, or aborts. Validates the
# filename shape (digits only) + regular-file — a malformed name must never
# reach the remote shell quoted sites. Call as a plain statement, NEVER inside
# $() — abort() inside a substitution is swallowed (loud-stop swallow class).
latest_handoff() {
  local f
  f="$(ls -td "$REPO"/docs/agents/wayfinder-*-handoff.md 2>/dev/null | head -1 | xargs -n1 basename 2>/dev/null || true)"
  [[ -n "$f" ]] || abort "$1"
  [[ "$f" =~ ^wayfinder-[0-9]+-handoff\.md$ ]] || abort "unexpected handoff filename — the switch bootstraps from docs/agents/wayfinder-<N>-handoff.md"
  [[ -f "$REPO/docs/agents/$f" ]] || abort "handoff path is not a regular file — remove the directory and re-run"
  HANDOFF="$f"
}

# check_authkey KEY EMPTY_ABORT_MSG — a pasted Tailscale auth key must be
# non-empty and charset-clean (it lands inside single quotes on the remote shell).
check_authkey() {
  [[ -n "$1" ]] || abort "$2"
  [[ "$1" =~ ^[A-Za-z0-9_-]+$ ]] || abort "invalid auth key (letters, digits, hyphens, underscores only)"
}

# _ask_config — the 7 one-time questions (hints + asks + writes). Re-used by
# both the first-run path and the "re-ask all" path of a re-run.
_ask_config() {
  note "MODE: full = wayfinder daemon + Coolify deploy (this project); app-only = just the app (no daemon)."
  ask MODE "Mode" full
  write_env MODE "$MODE"

  note "SSH_MODE: tailnet = SSH only over Tailscale (no public port, simpler + stronger); public = extra port + fail2ban."
  ask SSH_MODE "SSH access" tailnet
  write_env SSH_MODE "$SSH_MODE"

  note "TS_HOSTNAME: the VM's name in the Oracle console AND its Tailscale node name — they must match (case-insensitively); keep it unique on your tailnet."
  ask TS_HOSTNAME "Tailscale/instance hostname" company-app-vps
  write_env TS_HOSTNAME "$TS_HOSTNAME"

  note "VPS_USER: the SSH username on the VM — Oracle's Ubuntu 24.04 image uses 'ubuntu'."
  ask VPS_USER "Ubuntu username on the VPS" ubuntu
  write_env VPS_USER "$VPS_USER"

  note "REPO_URL: the git URL the VPS clones and Coolify deploys — defaults to this checkout's origin (git remote get-url origin)."
  ask REPO_URL "Git repository URL" "$(git -C "$REPO" remote get-url origin 2>/dev/null || true)"
  write_env REPO_URL "$REPO_URL"

  note "DEPLOY_BRANCH: the branch Coolify deploys and the daemon works on — defaults to the current branch."
  ask DEPLOY_BRANCH "Branch Coolify deploys" "$(git -C "$REPO" branch --show-current 2>/dev/null || true)"
  write_env DEPLOY_BRANCH "$DEPLOY_BRANCH"

  note "APP_DOMAIN: leave blank for a free api.<VPS_IP>.nip.io name (no DNS setup); a real domain must point its A record at the VPS IP. Re-runs keep a saved domain — delete the line in .wayfinder-vps.env to go back to nip.io."
  ask APP_DOMAIN "Public app domain (blank = nip.io from the VPS IP)"
  [[ -n "$APP_DOMAIN" ]] && write_env APP_DOMAIN "$APP_DOMAIN"
}

# _validate_config — every gate, run after BOTH the ask path and the keep-saved
# path (a hand-edited env file is caught the same way a typed value is).
_validate_config() {
  [[ "$MODE" == "full" || "$MODE" == "app-only" ]] || abort "MODE must be full or app-only"
  [[ "$SSH_MODE" == "tailnet" || "$SSH_MODE" == "public" ]] || abort "SSH_MODE must be tailnet or public"
  [[ "$TS_HOSTNAME" =~ ^[A-Za-z0-9][A-Za-z0-9-]*$ ]] || abort "hostname must start with a letter or digit (letters, digits, hyphens only — it feeds tailscale up + the OS hostname check)"
  [[ "$VPS_USER" =~ ^[A-Za-z][A-Za-z0-9_.-]*$ ]] || abort "invalid username (must start with a letter; letters, digits, dots, hyphens, underscores only)"
  [[ -n "$REPO_URL" ]] || abort "empty repository URL"
  [[ "$REPO_URL" =~ ^[A-Za-z0-9@._:/+~-]+$ && ( "$REPO_URL" =~ ^[A-Za-z][A-Za-z0-9+.-]*:// || "$REPO_URL" == git@* ) ]] || abort "REPO_URL must be a git URL (https://…, ssh://…, or git@…; no spaces or special characters)"
  [[ -n "$DEPLOY_BRANCH" ]] || abort "empty deploy branch"
  [[ "$DEPLOY_BRANCH" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] || abort "branch name must start with a letter or digit (letters, digits, dots, hyphens, underscores, slashes only)"
  git -C "$REPO" check-ref-format "refs/heads/$DEPLOY_BRANCH" || abort "not a valid git branch name (git's check-ref-format rules: no //, no .., no leading dot, no trailing / or .)"
  [[ -z "$APP_DOMAIN" || "$APP_DOMAIN" =~ ^[A-Za-z0-9.-]+$ ]] || abort "invalid domain (letters, digits, dots, hyphens only — or leave blank for the nip.io name)"
}

# ── Configuration (asked once; re-runs keep the saved values) ───────────────

_clear
printf '\n%s%s  VPS wizard — configure%s\n' "$BOLD" "$BLUE" "$RESET"
if [[ -n "$(_existing MODE || true)" && -n "$(_existing SSH_MODE || true)" && -n "$(_existing TS_HOSTNAME || true)" && -n "$(_existing VPS_USER || true)" && -n "$(_existing REPO_URL || true)" && -n "$(_existing DEPLOY_BRANCH || true)" ]]; then
  say "Saved config found — re-runs keep it: one gate, then the summary."
  note "mode: $(_existing MODE) | ssh: $(_existing SSH_MODE) | hostname: $(_existing TS_HOSTNAME) | user: $(_existing VPS_USER)"
  note "repo: $(_existing REPO_URL) | branch: $(_existing DEPLOY_BRANCH)"
  _keep_reply=""
  printf '  %sKeep this saved config? %s[Enter = keep, n = re-ask all]%s ' "$YELLOW" "$DIM" "$RESET"
  read -r _keep_reply || true
  if [[ ! "$_keep_reply" =~ ^[Nn] ]]; then
    MODE="$(_existing MODE)"
    SSH_MODE="$(_existing SSH_MODE)"
    TS_HOSTNAME="$(_existing TS_HOSTNAME)"
    VPS_USER="$(_existing VPS_USER)"
    REPO_URL="$(_existing REPO_URL)"
    DEPLOY_BRANCH="$(_existing DEPLOY_BRANCH)"
    APP_DOMAIN="$(_existing APP_DOMAIN || true)"
  else
    _ask_config
  fi
else
  say "One-time setup questions — press Enter to accept the shown default (type when no default fits)."
  say "Have at hand (first run): the Oracle Cloud console (VM creation), the Tailscale admin console, and a GitHub PAT (full mode)."
  note "re-runs keep your answers — Enter re-confirms them (a blank domain stays blank)."
  _ask_config
fi
_validate_config

TOTAL_STAGES=23
TOTAL_MINUTES=101
[[ "$MODE" == "full" ]] && { TOTAL_STAGES=38; TOTAL_MINUTES=166; }
[[ "$SSH_MODE" == "public" ]] && { TOTAL_STAGES=$((TOTAL_STAGES + 1)); TOTAL_MINUTES=$((TOTAL_MINUTES + 3)); }

banner "Oracle Cloud VPS — ${MODE} setup (${SSH_MODE} ssh)"

printf '\n%s%s  Configuration summary%s\n' "$BOLD" "$BLUE" "$RESET"
note "mode: $MODE | ssh: $SSH_MODE | hostname: $TS_HOSTNAME | user: $VPS_USER"
note "repo: $REPO_URL | branch: $DEPLOY_BRANCH | domain: ${APP_DOMAIN:-auto nip.io from the VPS IP}"
note "secrets: tailscale auth key + GitHub PAT (full mode) skipped when already configured; Coolify admin re-confirmed each run (Enter keeps current)."
pause "Summary above — press Enter to begin (Ctrl-C now to abort; a re-run re-asks with saved values)"

# ── Phase 0 — pre-flight (this machine) ────────────────────────────────────

stage "Pre-flight — branch state" 2
say "Your session record before the move:"
git -C "$REPO" log --oneline -1
note "branch: $(git -C "$REPO" branch --show-current 2>/dev/null || echo '?') — ahead of origin by $(git -C "$REPO" rev-list --count origin/master..HEAD 2>/dev/null || echo '?') commits"
git -C "$REPO" status --short | head -10 || true
if [[ "$MODE" == "full" ]] && command -v gh >/dev/null 2>&1; then
  gh issue list --state open --limit 10 || true
else
  note "gh issue list skipped (app-only mode or gh missing)"
fi
if [[ "$MODE" == "app-only" ]]; then
  if pgrep -f wayfinder-loop.sh >/dev/null 2>&1; then
    note "local wayfinder daemon still running — app-only mode will NOT move it (leave it or kill it yourself)"
  else
    note "no wayfinder daemon running locally"
  fi
fi
pause "Noted the session number + branch state"

stage "Push the branch now?" 4
if [[ "$MODE" == "full" ]]; then
  say "The VPS needs $DEPLOY_BRANCH on GitHub to clone it (and Coolify pulls it too)."
  say "Pushing now is safe — sessions commit locally, they don't push."
else
  say "Coolify pulls $DEPLOY_BRANCH from GitHub — push the branch now so the deploy sees it."
fi
if confirm "Push the branch to origin now"; then
  git -C "$REPO" push
  note "pushed (pre-push gate ~3 min)"
else
  if [[ "$MODE" == "full" ]]; then
    warn "deferred — the branch reaches origin at the switch push; the Coolify app stage will push first if it is behind"
  else
    warn "deferred — the Coolify app stage will push first if it is behind"
  fi
fi

# ── Phase 1 — Oracle VM + first access ─────────────────────────────────────

stage "SSH key" 1
if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
  note "key exists: $HOME/.ssh/id_ed25519.pub"
else
  say "No SSH key on this machine — creating one (empty passphrase)."
  confirm "Create ed25519 key at ~/.ssh/id_ed25519?" || { warn "create it yourself: ssh-keygen -t ed25519"; pause "key created?"; }
  if [[ ! -f "$HOME/.ssh/id_ed25519.pub" ]]; then
    mkdir -p "$HOME/.ssh" && ssh-keygen -q -t ed25519 -N "" -C "$(whoami)@$(hostname)-vps" -f "$HOME/.ssh/id_ed25519"
  fi
fi
note "your public key (paste into the Oracle console next):"
cat "$HOME/.ssh/id_ed25519.pub"

stage "Oracle console — create the VM" 15
open_url "https://cloud.oracle.com"
step "Sign in → Compute → Instances → Create instance"
step "Name: $TS_HOSTNAME (the OS hostname must match the tailnet hostname check)"
step "Image: Ubuntu 24.04 (aarch64 ARM64)"
step "Shape: VM.Standard.A1.Flex — set 2 OCPUs / 12 GB RAM (the free-tier cap)"
warn "A1 is often 'Out of capacity' in busy regions — retry your home region or a different availability domain"
step "Boot volume: 47 GB or larger (free tier includes 200 GB total)"
step "Networking: assign a RESERVED public IPv4 if offered (ephemeral works too — but a reserved IP keeps the nip.io name stable)"
step "Add SSH key: paste the public key shown below"
note "your public key (paste into the console next):"
cat "$HOME/.ssh/id_ed25519.pub"
note "No extra ingress — everything binds localhost; only SSH (22) is needed at first"
pause "Instance created — note its public IP"

stage "Capture the public IP" 2
ask VPS_IP "Paste the instance public IP:"
[[ -n "$VPS_IP" ]] || abort "empty IP — cannot continue"
[[ "$VPS_IP" =~ ^$IPV4_RE$ ]] || abort "invalid IPv4 — paste the instance public IP from the Oracle console"
[[ "$VPS_IP" != 127.* && "$VPS_IP" != 0.0.0.0 && "$VPS_IP" != 10.* && "$VPS_IP" != 192.168.* && "$VPS_IP" != 169.254.* && "$VPS_IP" != 172.1[6-9].* && "$VPS_IP" != 172.2[0-9].* && "$VPS_IP" != 172.3[0-1].* ]] || abort "that is a private/loopback address — paste the instance's PUBLIC IP from the Oracle console"
write_env VPS_IP "$VPS_IP"
pause "Press Enter to test SSH (first connect accepts the host key)"

stage "Verify SSH via public IP" 2
if [[ -n "$(_existing TS_IP || true)" ]]; then
  note "tailnet already joined (TS_IP saved) — skipping the public-IP ssh check (22 is off the security list by design in tailnet mode)"
else
  note "connecting…"
  if ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20 "$VPS_USER@$VPS_IP" 'uname -m; lsb_release -d; hostname'; then
    note "ssh works"
  else
    warn "ssh failed — check the IP, the key, and that the instance is RUNNING (not Provisioning/Stopped)"
    pause "Fixed? Press Enter to retry" && ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=20 "$VPS_USER@$VPS_IP" 'uname -m' || abort "ssh still failing — re-check the IP, the key, and that the instance is RUNNING (if the IP was reused by a new VM, delete its stale ~/.ssh/known_hosts entry)"
  fi
fi

# ── Phase 2 — Tailscale ────────────────────────────────────────────────────

stage "Tailscale auth key" 2
if [[ -z "$(_existing TS_IP || true)" ]]; then
  open_url "https://login.tailscale.com/admin/settings/keys"
  step "Generate an auth key (ephemeral is fine — it is used once)"
  ask_secret TS_AUTHKEY "Paste the Tailscale auth key:"
else
  note "tailnet already configured (TS_IP saved) — no auth key needed on re-runs"
fi

stage "Join the tailnet" 5
TS_SAVED="$(_existing TS_IP || true)"
if [[ -n "$TS_SAVED" ]] \
   && ssh -o ConnectTimeout=10 "$VPS_USER@$TS_SAVED" 'hostname' 2>/dev/null | grep -qiF -- "$TS_HOSTNAME"; then
  TS_IP="$TS_SAVED"
  note "already on the tailnet at $TS_SAVED (hostname $TS_HOSTNAME) — skipping"
else
  TS_AUTHKEY="${TS_AUTHKEY:-}"
  if [[ -z "$TS_AUTHKEY" ]]; then
    warn "no saved auth key — paste a fresh one (if the old box is gone, also delete the TS_IP line from $ENV_FILE)"
    ask_secret TS_AUTHKEY "Paste the Tailscale auth key:"
  fi
  check_authkey "$TS_AUTHKEY" "empty auth key — cannot join the tailnet"
  note "installing tailscale on the VPS and joining (via public IP)…"
  ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" \
    'curl -fsSL https://tailscale.com/install.sh | sudo sh'
  if ! ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" \
       "sudo tailscale up --authkey '$TS_AUTHKEY' --hostname '$TS_HOSTNAME'"; then
    warn "tailscale up failed — the saved auth key may be consumed or expired (if the tailscale daemon itself is down: sudo systemctl start tailscaled)"
    TS_AUTHKEY=""
    ask_secret TS_AUTHKEY "Paste a NEW auth key (Enter on empty aborts):"
    check_authkey "$TS_AUTHKEY" "no new key — aborting"
    ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" \
      "sudo tailscale up --authkey '$TS_AUTHKEY' --hostname '$TS_HOSTNAME'" || abort "tailscale up failed again — investigate on the VPS"
  fi
  TS_IP="$(ssh -o StrictHostKeyChecking=accept-new "$VPS_USER@$VPS_IP" 'tailscale ip -4' | tr -d '[:space:]')" || TS_IP=""
  [[ -n "$TS_IP" ]] || { warn "no tailnet IP — is the auth key valid/expired?"; pause "fix, then press Enter" ; TS_IP="$(ssh "$VPS_USER@$VPS_IP" 'tailscale ip -4' | tr -d '[:space:]')" || abort "still no tailnet IP — fix tailscale on the VPS, then re-run" ; }
  [[ "$TS_IP" =~ ^$IPV4_RE$ ]] || abort "could not read a valid tailnet IP from the VPS — tailscale up may still be pending; re-run to re-join"
  write_env TS_IP "$TS_IP"
fi
note "tailnet IP: $TS_IP"
warn "if an OLD $TS_HOSTNAME node is still alive on the tailnet (deleted VM?), delete it in the tailscale admin console — a stale node with the same name would be mistaken for this VPS"
if ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 "$VPS_USER@$TS_IP" 'true'; then
  note "✓ ssh via tailnet works — all later stages use the tailnet IP"
else
  warn "ssh over tailnet failed — is this machine logged into the same tailnet?"
  pause "Press Enter once ssh $VPS_USER@$TS_IP works"
fi

stage "Disable tailscale key expiry" 2
warn "Tailscale node keys expire after 180 days by default. When the key expires the node drops OFF the tailnet — and with ${SSH_MODE} ssh that is a LOCKOUT."
open_url "https://login.tailscale.com/admin/machines"
step "Find $TS_HOSTNAME → the ⋮ menu → Disable Key Expiry"
step "Confirm the row now shows key expiry disabled"
pause "Key expiry disabled for the node?"

# ssh/scp helpers — everything below rides the tailnet.
vps()   { ssh -o ConnectTimeout=15 "$VPS_USER@$TS_IP" "$@"; }
vpsscp() { scp -o ConnectTimeout=15 "$@"; }

# ── Phase 3 — bootstrap (scripted over tailnet) ────────────────────────────

stage "Base packages (all modes)" 6
vps 'sudo apt-get update && sudo apt-get install -y curl git unzip docker.io docker-compose-v2'
vps 'docker --version && docker compose version'
vps 'sudo usermod -aG docker '"$VPS_USER"' && sudo systemctl enable --now docker'
note "docker group applies to new sessions — each stage is a fresh ssh, so it is already active"

if [[ "$MODE" == "full" ]]; then

stage "Base packages (full mode extras)" 4
vps 'sudo apt-get install -y openjdk-21-jdk tmux npm gh'
vps 'java -version 2>&1 | head -1; tmux -V; gh --version | head -1'

stage "Android SDK (aarch64 support + platform 36)" 8
if vps 'test -d ~/android-sdk/platforms/android-36'; then
  note "Android SDK already installed — skipping"
else
  if vps '[ "$(uname -m)" = aarch64 ]'; then
    note "aarch64 host: AGP ships an x86_64-only aapt2 (no linux-arm64 on the Maven repo) — first make x86_64 binaries runnable via qemu binfmt + the amd64 loader"
    vps 'if [ -f /proc/sys/fs/binfmt_misc/qemu-x86_64 ]; then echo "x86_64 binfmt already registered"; else sudo apt-get install -y qemu-user-static binfmt-support >/dev/null; fi'
    vps 'if [ -f /lib64/ld-linux-x86-64.so.2 ]; then echo "amd64 loader present"; else sudo dpkg --add-architecture amd64 && sudo tee /etc/apt/sources.list.d/amd64.sources >/dev/null <<APTEOF
Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main universe restricted multiverse
Architectures: amd64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
APTEOF
sudo apt-get update >/dev/null && sudo apt-get install -y libc6:amd64 libstdc++6:amd64 zlib1g:amd64 >/dev/null; fi'
  fi
  vps 'mkdir -p ~/android-sdk/cmdline-tools && cd /tmp && if [ -x ~/android-sdk/cmdline-tools/latest/bin/sdkmanager ]; then echo "cmdline-tools present"; else curl -fSLO https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip && unzip -q commandlinetools-linux-11076708_latest.zip -d ~/android-sdk/cmdline-tools && mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest && rm -f commandlinetools-linux-11076708_latest.zip; fi'
  vps 'yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null 2>&1; ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0" >/dev/null 2>&1'
  vps 'grep -q ANDROID_HOME ~/.bashrc || echo -e "\n# Android SDK (installed by wizard)\nexport ANDROID_HOME=\$HOME/android-sdk\nexport ANDROID_SDK_ROOT=\$ANDROID_HOME\nexport PATH=\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/cmdline-tools/latest/bin:\$PATH" >> ~/.bashrc'
  vps 'grep -q sdk.dir ~/company_app/local.properties 2>/dev/null || echo "sdk.dir=$HOME/android-sdk" >> ~/company_app/local.properties'
fi
if vps '~/android-sdk/cmdline-tools/latest/bin/sdkmanager --list_installed 2>/dev/null | grep -q "platforms;android-36"'; then
  note "✓ SDK packages verified on the VPS (platform 36 + build-tools 36.0.0)"
else
  warn "SDK install did NOT verify on the VPS — the warm gate will fail"
  confirm "Continue anyway?" || exit 1
fi

stage "GitHub CLI auth" 5
if vps 'gh auth status' 2>/dev/null; then
  note "gh already authenticated on the VPS — skipping"
else
  open_url "https://github.com/settings/tokens/new"
  step "Create a CLASSIC token with the repo scope (covers issues + git-credential)"
  ask_secret GH_PAT "Paste the GitHub PAT (repo scope):"
  [[ -n "$GH_PAT" ]] || abort "empty PAT — cannot auth gh on the VPS"
  printf '%s' "$GH_PAT" | vps 'gh auth login --with-token'
  vps 'gh auth status'
  note "PAT consumed by the VPS — nothing written to disk locally"
fi

stage "opencode2 (pinned)" 3
vps 'sudo npm install -g @opencode-ai/cli@0.0.0-next-17444'
if vps 'opencode2 --version | grep -q next-17444'; then
  note "✓ version pin matched"
else
  warn "opencode2 version does NOT match the pin (next-17444) — the daemon needs the same build as the local box"
  pause "reinstall or fix, then press Enter"
fi

stage "Copy opencode config + keys" 3
if vps 'test -d ~/.config/opencode' 2>/dev/null; then
  note "opencode config already on the VPS (re-run) — skipping the scp"
  warn "if config/auth.json changed locally since the copy, re-copy by hand: scp -r $HOME/.config/opencode $VPS_USER@$TS_IP:~/.config/ and restart the service"
else
  vps 'mkdir -p ~/.config ~/.local/share/opencode'
  vpsscp -r "$HOME/.config/opencode" "$VPS_USER@$TS_IP":~/.config/
  vpsscp "$HOME/.local/share/opencode/auth.json" "$VPS_USER@$TS_IP":~/.local/share/opencode/auth.json
  warn "deliberately NOT copying ~/.local/share/opencode/opencode.db (session state — VPS starts fresh)"
  vps 'du -sh ~/.config/opencode; wc -c ~/.local/share/opencode/auth.json'
fi

stage "Start the opencode service" 2
if vps 'opencode2 api get /api/model'; then
  note "opencode service already serving (re-run) — the model response above is the live probe"
  warn "if opencode config/auth.json changed since the service started, it serves the OLD config — restart the service on the VPS if unsure"
else
  vps 'opencode2 serve --service' || abort "opencode service failed to start"
  sleep 3
  if ! vps 'opencode2 api get /api/model'; then
    warn "model probe failed — the service may still be binding; retry below"
    pause "Press Enter to retry the probe"
    vps 'opencode2 api get /api/model' || abort "model probe still failing — check the service on the VPS"
  fi
fi
pause "Does the model response above look right? (not an error)"

stage "Clone the repo" 3
if vps 'test -d ~/company_app/.git'; then
  note "repo already cloned — skipping"
else
  vps "git clone '$REPO_URL' ~/company_app"
fi
if vps "git -C ~/company_app switch '$DEPLOY_BRANCH'"; then
  note "branch checked out"
else
  warn "branch not on origin yet — it lands at the switch push; the switch stage checks it out"
  vps 'git -C ~/company_app switch master 2>/dev/null || true'
fi
vps 'git -C ~/company_app log --oneline -1'

stage "Copy secrets (.env, .wayfinder-loop.env)" 2
[[ -f "$REPO/.env" ]] && vpsscp "$REPO/.env" "$VPS_USER@$TS_IP":~/company_app/.env
[[ -f "$REPO/.wayfinder-loop.env" ]] && vpsscp "$REPO/.wayfinder-loop.env" "$VPS_USER@$TS_IP":~/company_app/.wayfinder-loop.env
warn "secrets now on the VPS — keep the ntfy topic + creds off any logs"
vps 'wc -c ~/company_app/.env ~/company_app/.wayfinder-loop.env'

stage "Postgres 18 (gate DB)" 4
vps 'cd ~/company_app && docker compose -f docker/docker-compose.yml up -d'
warn "compose publishes 5432 on 0.0.0.0 — Docker traffic bypasses ufw; the Oracle security list (default: only 22) blocks it — do NOT open 5432 in the console"
PG_OK=""
for i in $(seq 1 12); do
  sleep 10
  PG_STATUS="$(vps 'cd ~/company_app && docker compose -f docker/docker-compose.yml ps' 2>/dev/null || true)"
  if echo "$PG_STATUS" | grep -q healthy; then
    note "postgres healthy"; PG_OK=1; break
  fi
done
if [[ -z "$PG_OK" ]]; then
  warn "postgres not healthy after ~2 min — the warm gate below will fail too. Check: docker compose -f docker/docker-compose.yml ps"
  confirm "Continue anyway?" || exit 1
fi

stage "Git hooks + ktlint" 2
vps 'cd ~/company_app && bash scripts/setup-hooks.sh'

stage "Warm the build gate" 16
GATE_CMD="cd ~/company_app && nohup ./gradlew :backend:detekt :backend:ktlintCheck :backend:test :composeApp:compileKotlinDesktop :composeApp:compileDebugKotlinAndroid :composeApp:testDebugUnitTest > /tmp/gate-warm.log 2>&1 &"
LAST_BUILD="$(vps 'grep -E "BUILD (SUCCESSFUL|FAILED)" /tmp/gate-warm.log 2>/dev/null | tail -1' || true)"
if [[ "$LAST_BUILD" == *"FAILED"* ]]; then
  warn "gate warm FAILED in an earlier run — the first VPS session commit would break."
  note "relaunch by hand: ssh $VPS_USER@$TS_IP '$GATE_CMD'"
  confirm "Continue anyway (gate NOT warm)?" || exit 1
elif [[ "$LAST_BUILD" == *"SUCCESSFUL"* ]]; then
  note "gate already warm from a previous run (BUILD SUCCESSFUL on record)"
else
  LOG_RC=0
  vps 'test -f /tmp/gate-warm.log' >/dev/null 2>&1 || LOG_RC=$?
  case "$LOG_RC" in
    0) note "a previous gate run is in progress or stale — polling it (no relaunch: two Gradle builds on 2 OCPU would contend)" ;;
    1) note "first Gradle run downloads the toolchain + deps (~10-15 min). Launched in background; the wizard polls."
       vps "$GATE_CMD" || abort "launch failed — relaunch by hand: ssh $VPS_USER@$TS_IP '$GATE_CMD'" ;;
    *) warn "could not check the VPS gate log (ssh failed) — retrying once"
       sleep 3
       if ! vps 'test -f /tmp/gate-warm.log' >/dev/null 2>&1; then
         abort "still cannot check the gate log — aborting before the deploy/switch"
       fi
       note "a previous gate run is in progress or stale — polling it" ;;
  esac
  STALL=0
  LAST_CHANGE="$(vps 'stat -c %Y /tmp/gate-warm.log' 2>/dev/null || true)"
  for i in $(seq 1 40); do
    sleep 30
    last="$(vps 'tail -n 1 /tmp/gate-warm.log' 2>/dev/null || true)"
    printf '  %s%s\n' "$DIM" "$last"
    if vps 'grep -qE "BUILD (SUCCESSFUL|FAILED)" /tmp/gate-warm.log' 2>/dev/null; then break; fi
    NEW_CHANGE="$(vps 'stat -c %Y /tmp/gate-warm.log' 2>/dev/null || true)"
    if [[ -n "$NEW_CHANGE" && "$NEW_CHANGE" == "$LAST_CHANGE" ]]; then
      STALL=$((STALL + 1))
      if [[ $STALL -ge 10 ]]; then
        warn "gate log unchanged for ~5 min — the build likely died"
        note "relaunch by hand: ssh $VPS_USER@$TS_IP '$GATE_CMD'"
        break
      fi
    else
      STALL=0
    fi
    LAST_CHANGE="$NEW_CHANGE"
  done
  LAST_BUILD="$(vps 'grep -E "BUILD (SUCCESSFUL|FAILED)" /tmp/gate-warm.log 2>/dev/null | tail -1' || true)"
  if [[ "$LAST_BUILD" == *"SUCCESSFUL"* ]]; then
    note "✓ gate warm — BUILD SUCCESSFUL"
  elif [[ "$LAST_BUILD" == *"FAILED"* ]]; then
    warn "gate warm FAILED — the first VPS session commit would break. Fix before continuing."
    confirm "Continue anyway?" || exit 1
  else
    warn "gate warm neither succeeded nor failed — investigate before continuing."
    confirm "Continue anyway?" || exit 1
  fi
fi

else
  note "full-mode stages skipped (app-only mode) — Coolify builds in containers; the VPS itself needs no JDK/Gradle/gh"
fi

# ── Phase 4 — harden ───────────────────────────────────────────────────────

stage "Firewall (ufw)" 3
vps 'sudo apt-get install -y ufw'
if [[ "$SSH_MODE" == "public" ]]; then
  vps "sudo ufw default deny incoming && sudo ufw default allow outgoing && sudo ufw allow in on tailscale0 && sudo ufw allow 80/tcp && sudo ufw allow 443/tcp && sudo ufw allow 51920/tcp && sudo ufw allow 41641/udp && sudo ufw --force enable"
else
  vps 'sudo ufw default deny incoming && sudo ufw default allow outgoing && sudo ufw allow in on tailscale0 && sudo ufw allow 80/tcp && sudo ufw allow 443/tcp && sudo ufw allow 41641/udp && sudo ufw --force enable'
fi
vps 'sudo ufw status verbose'
if [[ "$SSH_MODE" == "public" ]]; then
  note "tailnet ssh = 22 via tailscale0; org admins = 51920/tcp public (key-only, fail2ban); 80/443 public for Coolify + the app; 41641/udp = tailscale direct connections"
else
  note "ssh = tailnet only (via tailscale0); 80/443 public for Coolify + the app; 41641/udp = tailscale direct connections"
fi

stage "SSH hardening" 2
if [[ "$SSH_MODE" == "public" ]]; then
  vps 'printf "Port 22\nPort 51920\nPermitRootLogin no\nPasswordAuthentication no\n" | sudo tee /etc/ssh/sshd_config.d/99-hardening.conf'
  # Ubuntu 24.04 socket-activates sshd: the ssh.socket owns the listening
  # sockets and ignores sshd_config Port — switch to the classic service and
  # RESTART it (enable alone is a no-op when sshd is already active via the
  # socket; the restart rebinds with the new config).
  if vps 'sudo systemctl disable --now ssh.socket 2>/dev/null || true; sudo systemctl enable --now ssh && sudo systemctl restart ssh && sudo systemctl daemon-reload'; then
    note "sshd reconfigured"
  else
    warn "sshd reconfiguration failed — fix: ssh $VPS_USER@$TS_IP 'sudo systemctl disable --now ssh.socket; sudo systemctl restart ssh'. If tailnet ssh is DEAD too, use Oracle Console → your instance → Console connection (serial) — it is hypervisor-level and bypasses ufw."
    pause "sshd fixed?"
  fi
  if vps 'sudo ss -tln | grep -q ":22 " && sudo ss -tln | grep -q ":51920 "'; then
    note "✓ sshd listening on 22 (tailnet) and 51920 (public)"
  else
    warn "sshd not listening on both ports — check: sudo ss -tln; fix: sudo systemctl disable --now ssh.socket; sudo systemctl restart ssh. If ssh is dead: Oracle Console → instance → Console connection (serial)."
    pause "ports fixed?"
  fi
  vps 'sudo sshd -T | grep -E "^(permitrootlogin|passwordauthentication)"'
  note "for console recovery: set a password NOW — sudo passwd $VPS_USER (sshd won't accept it; it only works at the Oracle serial console)"
else
  vps 'printf "PermitRootLogin no\nPasswordAuthentication no\n" | sudo tee /etc/ssh/sshd_config.d/99-hardening.conf && sudo systemctl restart ssh'
  vps 'sudo sshd -T | grep -E "^(permitrootlogin|passwordauthentication)"'
fi

if [[ "$SSH_MODE" == "public" ]]; then

stage "Fail2ban (public ssh)" 3
vps 'sudo apt-get install -y fail2ban'
vps 'printf "[sshd]\nenabled = true\nport = 22,51920\n" | sudo tee /etc/fail2ban/jail.d/sshd-ports.conf && sudo systemctl restart fail2ban'
if vps 'sudo fail2ban-client status sshd' >/dev/null 2>&1; then
  note "✓ fail2ban jail up (ports 22,51920 configured)"
else
  warn "fail2ban jail check failed — inspect: sudo fail2ban-client status sshd"
fi
note "key-only auth already blocks password guessing"

fi

stage "Unattended security upgrades" 2
vps 'sudo apt-get install -y unattended-upgrades && sudo systemctl enable --now unattended-upgrades'
vps 'sudo sed -i "s|//[[:space:]]*\"\${distro_id}:\${distro_codename}\";|\"\${distro_id}:\${distro_codename}\";|" /etc/apt/apt.conf.d/50unattended-upgrades'
vps 'systemctl is-enabled unattended-upgrades'

stage "Oracle security list (2nd firewall layer)" 5
open_url "https://cloud.oracle.com"
step "Networking → Virtual cloud networks → your VCN → Security Lists → Default Security List"
step "Edit ingress rules: REMOVE 22/tcp from 0.0.0.0/0"
if [[ "$SSH_MODE" == "public" ]]; then
  step "ADD 80/tcp, 443/tcp AND 51920/tcp from 0.0.0.0/0 (app, Coolify proxy, org-admin ssh on 51920)"
else
  step "ADD 80/tcp and 443/tcp from 0.0.0.0/0 (Coolify + the app)"
  note "tailnet ssh rides tailscale0 — unaffected by the security list"
fi
note "Security list + ufw = the two independent layers from docs/architecture.md"
pause "Security list updated?"

stage "Oracle idle-reclaim heartbeat" 2
warn "Oracle stops Always-Free instances idle for 7 days (CPU p95 <20%, net <20%, mem <20%). Coolify's footprint alone keeps memory above 20% of 12 GB — this cron covers the CPU leg as belt-and-braces."
vps 'printf "%s\n" "* * * * * root nice -n 19 timeout 30 yes > /dev/null 2>&1" | sudo tee /etc/cron.d/idle-heartbeat && sudo chmod 644 /etc/cron.d/idle-heartbeat'
vps 'sudo grep -c "" /etc/cron.d/idle-heartbeat'

# ── Phase 5 — Coolify + app deploy ─────────────────────────────────────────

stage "Install Coolify" 8
note "installing (downloads ~5 min)…"
vps 'curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash'
note "waiting for the Coolify API (first boot pulls images)…"
for i in $(seq 1 12); do
  sleep 10
  if vps 'curl -sf http://127.0.0.1:8000/api/health' >/dev/null 2>&1; then
    note "✓ Coolify API is up"; break
  fi
  [[ $i -eq 12 ]] && warn "Coolify API not up after ~2 min — check: sudo docker ps | grep coolify"
done

stage "Coolify dashboard first run" 5
open_url "http://$TS_IP:8000"
step "Create the admin account (email + password) — the wizard remembers them for re-runs"
ask COOLIFY_ADMIN_EMAIL "Coolify admin email:"
write_env COOLIFY_ADMIN_EMAIL "$COOLIFY_ADMIN_EMAIL"
ask_secret COOLIFY_ADMIN_PASSWORD "Coolify admin password:"
write_env COOLIFY_ADMIN_PASSWORD "$COOLIFY_ADMIN_PASSWORD"
step "Instance domain: leave as-is (http://$TS_IP:8000)"
step "Skip/close any onboarding prompts (notifications, etc.)"
pause "Dashboard visible?"

stage "App Dockerfile" 4
if [[ "$MODE" == "full" ]]; then
  if [[ ! -f "$REPO/backend/Dockerfile" ]]; then
    warn "backend/Dockerfile missing — create it (multi-stage: gradle wrapper → temurin 21 → installDist), then commit + push"
    pause "Dockerfile in place and pushed?"
  fi
  if [[ -f "$REPO/backend/Dockerfile" ]]; then
    note "backend/Dockerfile present ✓"
    if git -C "$REPO" status --porcelain backend/Dockerfile | grep -q .; then
      confirm "Commit + push the Dockerfile now (Coolify needs it on GitHub)?" && \
        git -C "$REPO" add backend/Dockerfile && \
        git -C "$REPO" commit -m "feat(infra): backend Dockerfile for Coolify deploy" && \
        git -C "$REPO" push
    fi
  fi
else
  if ls "$REPO"/Dockerfile "$REPO"/backend/Dockerfile >/dev/null 2>&1; then
    note "Dockerfile present ✓ (Coolify will use it)"
  else
    warn "no Dockerfile found in the repo — Coolify can build with Nixpacks (auto-detect), or add a Dockerfile and push it"
    pause "Dockerfile in place and pushed? (or note to use Nixpacks)"
  fi
fi

stage "Coolify — Postgres resource" 5
open_url "http://$TS_IP:8000"
step "Projects → New Project (e.g. company) → inside it: + New Resource → Postgres"
if [[ "$MODE" == "full" ]]; then
  step "Set POSTGRES_DB / POSTGRES_USER / POSTGRES_PASSWORD to the values from your repo .env (paste from below):"
  note "  — values below are read from your local .env —"
  for k in POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD; do
    note "  $k=$(env_val "$k")"
  done
else
  step "Set a DB name, user and password of your choice (or from your app's config — your choice)"
fi
step "Deploy the Postgres resource and wait for it to run"
pause "Postgres resource running? Note its internal hostname (usually 'postgres')"

stage "Coolify — the app resource" 8
# Coolify pulls from GitHub — the branch must be current on origin BEFORE the deploy.
git -C "$REPO" fetch origin --quiet || true
if git -C "$REPO" rev-parse --verify -q "origin/$DEPLOY_BRANCH" >/dev/null 2>&1; then
  BEHIND=$(git -C "$REPO" rev-list --count "origin/$DEPLOY_BRANCH..HEAD" 2>/dev/null || echo 999)
else
  BEHIND=999
fi
if [[ "$BEHIND" != "0" ]]; then
  note "branch is $BEHIND commit(s) ahead of origin — pushing so Coolify deploys the current code."
  if confirm "Push now?"; then
    git -C "$REPO" push origin "$DEPLOY_BRANCH" || warn "push FAILED — Coolify will deploy the OLD commit; the switch push retries"
  else
    warn "skipped — Coolify deploys whatever is on origin (may be stale)"
  fi
fi
LOCAL_ORIGIN="$(git -C "$REPO" remote get-url origin 2>/dev/null || true)"
if [[ -n "$LOCAL_ORIGIN" ]]; then
  NORM_LOCAL="$(printf '%s' "$LOCAL_ORIGIN" | sed -E 's#^[a-z]+://##; s#^git@##; s#^[^@]+@##; s#:([^0-9])#/\1#; s#\.git$##')"
  NORM_REPO="$(printf '%s' "$REPO_URL" | sed -E 's#^[a-z]+://##; s#^git@##; s#^[^@]+@##; s#:([^0-9])#/\1#; s#\.git$##')"
  [[ "$NORM_LOCAL" == "$NORM_REPO" ]] || warn "this checkout's origin ($LOCAL_ORIGIN) differs from the Coolify repo ($REPO_URL) — pushes land elsewhere; Coolify pulls $REPO_URL"
fi
open_url "http://$TS_IP:8000"
step "+ New Resource → Public Repository"
step "Git repository: $REPO_URL"
step "Branch: $DEPLOY_BRANCH"
step "Build pack: Dockerfile (or Nixpacks if no Dockerfile)"
if [[ "$MODE" == "full" ]]; then
  step "Dockerfile location: /backend/Dockerfile"
  step "Ports Exposes: $(env_val APP_PORT 'your APP_PORT from .env')"
else
  step "Ports Exposes: your app's port"
fi
DOMAIN="${APP_DOMAIN:-api.$VPS_IP.nip.io}"
step "Domains: $DOMAIN (enable HTTPS — Let's Encrypt)"
if [[ -n "$APP_DOMAIN" ]]; then
  warn "you gave a real domain — make sure its A record points at $VPS_IP BEFORE the deploy (DNS propagation delays break the TLS issuance)"
else
  note "nip.io name derived from the VPS IP — no DNS setup needed"
fi
if [[ "$MODE" == "full" ]]; then
  step "Environment variables — copy from the block below:"
  note "  APP_HOST=0.0.0.0"
  note "  APP_PORT=$(env_val APP_PORT '<APP_PORT from .env>')"
  note "  DB_HOST=postgres   # the Postgres resource's internal hostname"
  note "  DB_PORT=5432"
  note "  POSTGRES_DB=$(env_val POSTGRES_DB)"
  note "  POSTGRES_USER=$(env_val POSTGRES_USER)"
  note "  POSTGRES_PASSWORD=$(env_val POSTGRES_PASSWORD)"
  note "  JWT_SECRET=$(env_val JWT_SECRET)"
  note "  JWT_ISSUER=$(env_val JWT_ISSUER)"
  note "  JWT_AUDIENCE=$(env_val JWT_AUDIENCE)"
  note "  AUTH_DUMMY_PASSWORD=$(env_val AUTH_DUMMY_PASSWORD)"
  note "  (skip TEST_USERNAME/TEST_PASSWORD — test seeding stays off in prod)"
else
  step "Environment variables — the keys your app needs. Your local .env defines:"
  grep -oE '^[A-Z_]+=' "$REPO/.env" 2>/dev/null | tr -d '=' | sed 's/^/  /' || note "  (no .env found locally — enter the vars your app needs)"
  step "Copy the VALUES from your local .env; override DB_HOST=postgres and APP_HOST=0.0.0.0"
fi
step "Deploy, then watch the build log (~5-10 min first build)"
pause "Build finished (success or visible failure)?"

stage "Verify the deployed backend" 10
if confirm "Try the HTTPS health check now?"; then
  code="$(curl -sk -o /dev/null -w '%{http_code}' "https://$DOMAIN/health" || true)"
  note "https://$DOMAIN/health → HTTP $code"
  curl -sk "https://$DOMAIN/health" && echo || true
  if [[ "$code" == "200" ]]; then
    note "✓ deployed backend is live over HTTPS"
  else
    warn "not 200 — check the Coolify build log + app logs; DB_HOST must match the Postgres resource name"
    pause "press Enter after the deploy is fixed"
  fi
fi

# ── Phase 6 — the switch (CRITICAL: never two daemons; full mode only) ─────

if [[ "$MODE" == "full" ]]; then

stage "Boundary check" 2
latest_handoff "no handoff found in docs/agents/ — the switch bootstraps from one"
note "latest handoff: $HANDOFF"
git -C "$REPO" log --oneline -3
UNCOMMITTED_HANDOFF="$(git -C "$REPO" status --porcelain 2>/dev/null | grep "wayfinder-" || true)"
[[ -n "$UNCOMMITTED_HANDOFF" ]] && warn "the handoff is NOT committed yet — it must land before the switch"
pause "Session N complete — handoff committed, and the next session number is the one that handoff names?"

stage "Kill the local daemon" 2
warn "Rollback if anything fails below: tmux new -s wayfinder-loop && ./scripts/wayfinder-loop.sh"
if confirm "Kill the local wayfinder-loop daemon NOW (this is the switch)?"; then
  tmux kill-session -t wayfinder-loop 2>/dev/null || true
  sleep 2
  if tmux ls 2>/dev/null | grep -q wayfinder-loop || pgrep -f wayfinder-loop.sh >/dev/null; then
    warn "daemon still alive — kill it manually (tmux kill-session -t wayfinder-loop)"
    pause "daemon dead?"
  else
    note "✓ local daemon dead"
  fi
else
  warn "SWITCH ABORTED — the VPS daemon must never run while the local one lives."
  abort "Nothing was started; re-run the wizard later to resume (state is saved)"
fi

stage "Push the branch (carries the handoff)" 4
# Push AFTER the kill: anything a session committed up to the boundary lands in this push.
git -C "$REPO" fetch origin --quiet || true
if git -C "$REPO" rev-parse --verify -q "origin/$DEPLOY_BRANCH" >/dev/null 2>&1; then
  if [[ -n "$(git -C "$REPO" log --oneline "origin/$DEPLOY_BRANCH..HEAD" 2>/dev/null)" ]]; then
    git -C "$REPO" push origin "$DEPLOY_BRANCH" || abort "push FAILED — if the remote diverged: git fetch origin && git pull --rebase, then git push --force-with-lease; if the PRE-PUSH HOOK failed: fix the gate. Then re-run (the wizard resumes at this stage)"
    note "pushed (~3 min pre-push gate)"
  else
    note "already up to date"
  fi
else
  note "branch has no upstream — pushing it now"
  git -C "$REPO" push -u origin "HEAD:$DEPLOY_BRANCH" || abort "push FAILED — fix and re-run (the wizard resumes at this stage)"
fi

stage "Start the VPS daemon" 5
warn "Rollback: on the local box — tmux new -s wayfinder-loop && ./scripts/wayfinder-loop.sh (resumes its state file)"
# Re-derive the handoff AFTER the kill+push — the push just carried whatever the re-derive finds.
latest_handoff "no handoff to bootstrap — aborting before the VPS daemon start"
note "bootstrapping with: $HANDOFF"
if vps 'tmux has-session -t wayfinder-loop' >/dev/null 2>&1; then
  HAS_RC=0
else
  HAS_RC=$?
fi
if [[ "$HAS_RC" -eq 0 ]]; then
  note "VPS daemon session already exists — skipping (verify below); if the log shows no recent spawn, kill the session and re-run"
else
  if [[ "$HAS_RC" -ne 1 ]]; then
    warn "could not check the VPS tmux state (ssh failed) — refusing to touch a possibly live daemon"
    abort "rollback: tmux new -s wayfinder-loop && ./scripts/wayfinder-loop.sh"
  fi
  note "aligning the VPS checkout with origin (a local-only VPS commit from a partial run is discarded — origin is canonical)…"
  vps "cd ~/company_app && git fetch origin && (git switch -C '$DEPLOY_BRANCH' origin/'$DEPLOY_BRANCH' 2>/dev/null || git switch '$DEPLOY_BRANCH') && { git pull --ff-only || true; }" || abort "git alignment failed on the VPS — re-run resumes after the (dead) kill check"
  vps "test -f ~/company_app/docs/agents/$HANDOFF" || abort "handoff not in the VPS checkout — the pull or push is stale"
  LOCAL_SHA="$(sha256sum "$REPO/docs/agents/$HANDOFF" | cut -d' ' -f1)"
  VPS_SHA="$(vps "sha256sum ~/company_app/docs/agents/$HANDOFF" 2>/dev/null | cut -d' ' -f1 || true)"
  [[ -n "$VPS_SHA" ]] || abort "could not read the handoff checksum on the VPS (ssh failure?)"
  [[ "$LOCAL_SHA" == "$VPS_SHA" ]] || abort "handoff on the VPS differs from local — the pull or push is stale"
  note "✓ handoff present and identical on the VPS"
  vps "tmux new-session -d -s wayfinder-loop \"bash -lc 'cd ~/company_app && ./scripts/wayfinder-loop.sh --bootstrap $HANDOFF'\"" || abort "tmux start failed on the VPS"
fi
sleep 15
vps 'tail -n 20 ~/company_app/.wayfinder-loop.log' 2>/dev/null || true
note "expect a line like: spawned ses_… reading <handoff>.md"
pause "ntfy topic fired ('wayfinder session started')?"

stage "Post-migration checks" 3
if vps 'cd ~/company_app && gh issue view 89 --json number,title,state -q ".number + \" \" + .title + \" (\" + .state + \")\""'; then
  note "✓ map reachable from the VPS (gh issue view 89)"
else
  warn "gh issue view 89 FAILED on the VPS — check gh auth/network"
fi
if vps 'cd ~/company_app && git push --dry-run && gh issue list --state open'; then
  note "✓ dry-run shows the branch set; open-issue list confirms the tracker is reachable (runbook Phase 2 verify block)"
else
  warn "push --dry-run or issue list FAILED on the VPS — check git/gh state"
fi
note "first VPS pre-commit gate runs on the next session commit (watch it succeed end-to-end)"
note "k6 skipped (optional): pre-push warns + skips the load test on the VPS"
note "next session on the VPS works the map as usual — same branch, same issues"

else
  note "switch phase skipped (app-only mode) — nothing to move; the VPS is the app host only"
fi

finish
